# Generated by Django 4.2.6 on 2023-10-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100, verbose_name='Name')),
                ('group_name', models.CharField(max_length=100, verbose_name='Group name')),
                ('animal_latin_name', models.CharField(max_length=100, verbose_name='Latin name')),
                ('region_name', models.CharField(max_length=100, verbose_name='Region name')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('state_name', models.CharField(max_length=100, verbose_name='State name')),
            ],
        ),
    ]
